# service.yaml
apiVersion: apps/v1
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    nodePort: 30085
    protocol: TCP
    targetPort: 80
  selector: 
    app: nginx
  type: NodePort